# Generated by Django 2.2 on 2019-05-31 19:25

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['sucursal', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(default=None, max_length=75)),
                ('localidad', models.CharField(default=None, max_length=50)),
                ('contacto', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapiResto_Responsables.Mesa')),
            ],
            options={
                'ordering': ['mesa', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Anónimo', max_length=25)),
                ('comentario', models.TextField(blank=True)),
                ('valoracion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapiResto_Responsables.Sucursal')),
            ],
            options={
                'ordering': ['valoracion'],
            },
        ),
        migrations.AddField(
            model_name='mesa',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='RapiResto_Responsables.Sucursal'),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapiResto_Responsables.Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=75)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapiResto_Responsables.Sucursal')),
            ],
            options={
                'ordering': ['sucursal', 'nombre'],
                'unique_together': {('nombre', 'sucursal')},
            },
        ),
        migrations.CreateModel(
            name='AlimentoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapiResto_Responsables.Alimento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='RapiResto_Responsables.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='AlimentoCarta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapiResto_Responsables.Alimento')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapiResto_Responsables.Carta')),
            ],
        ),
        migrations.AddField(
            model_name='alimento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapiResto_Responsables.Categoria'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='recomendaciones',
            field=models.ManyToManyField(blank=True, related_name='_alimento_recomendaciones_+', to='RapiResto_Responsables.Alimento'),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('numero', 'sucursal')},
        ),
    ]
