# Generated by Django 2.2 on 2019-06-01 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RapiResto_Responsables', '0002_administradoralimentos_administradorcartas_repositor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RapiResto_Responsables.Sucursal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='administradorcartas',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='administradorcartas',
            name='user',
        ),
        migrations.RemoveField(
            model_name='repositor',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='repositor',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdministradorAlimentos',
        ),
        migrations.DeleteModel(
            name='AdministradorCartas',
        ),
        migrations.DeleteModel(
            name='Repositor',
        ),
    ]
