# Generated by Django 2.2.2 on 2019-06-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RapiResto_Responsables', '0003_auto_20190531_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RapiResto_Responsables.Sucursal'),
        ),
    ]
