# Generated by Django 2.2.2 on 2019-06-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RapiResto_Responsables', '0004_auto_20190609_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapiResto_Responsables.Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Opinion',
        ),
    ]
