# Generated by Django 2.2.2 on 2019-06-11 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RapiResto_Responsables', '0005_auto_20190611_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='pedido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RapiResto_Responsables.Pedido'),
        ),
    ]
