# Generated by Django 2.2.2 on 2019-06-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RapiResto_Responsables', '0006_auto_20190611_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='contenido',
        ),
    ]
