# Generated by Django 2.2.2 on 2019-06-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RapiResto_Responsables', '0008_auto_20190614_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='recomendaciones',
            field=models.ManyToManyField(blank=True, related_name='_alimento_recomendaciones_+', to='RapiResto_Responsables.Alimento'),
        ),
    ]
