# Generated by Django 2.2.2 on 2019-06-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RapiResto_Responsables', '0009_auto_20190614_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='optimized_images/'),
        ),
        migrations.AlterUniqueTogether(
            name='alimentocarta',
            unique_together={('alimento', 'carta')},
        ),
    ]
