# Generated by Django 2.2.2 on 2019-06-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RapiResto_Responsables', '0010_auto_20190616_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='latitud',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='longitud',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='carta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='optimized_images/'),
        ),
    ]
