# Generated by Django 2.2.2 on 2019-06-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RapiResto_Responsables', '0011_auto_20190620_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='latitud',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='longitud',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
    ]
